services:
  db:
    image: postgres:17-alpine
    container_name: new_project_db
    environment:
      POSTGRES_DB: new_project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"