spring:
  application:
    name: labourer-service
  Datasource:
    url: jdbc:postgresql://localhost:5432/labourer_db
    username: postgres
    password: postgres



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port:
    "8082"
