spring:
  application:
    name: auth-service
  Datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

server:
  port:
    8081
